version: '3.8'

networks:
  cropdeal-net:
    driver: bridge

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: cropdeal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vnaresh2004
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pvnaresh2004"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cropdeal-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cropdeal-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cropdeal-net

  eureka-server:
    build: ./eureka-server
    container_name: cropdeal-eureka-server
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    networks:
      - cropdeal-net

  api-gateway:
    build: ./api-gateway
    container_name: cropdeal-api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      - eureka-server
    networks:
      - cropdeal-net

  auth-service:
    build: ./auth-service
    container_name: cropdeal-auth-service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  user-service:
    build: ./user-sevice
    container_name: cropdeal-user-service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  crop-service:
    build: ./crop-service
    container_name: cropdeal-crop-service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_crop_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  price-service:
    build: ./price-service
    container_name: cropdeal-price-service
    restart: on-failure
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_price_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  negotiation-service:
    build: ./negotiation-service
    container_name: cropdeal-negotiation-service
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_negotiation_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  bidding-service:
    build: ./bidding-service
    container_name: cropdeal-bidding-service
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_bidding_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  wallet-service:
    build: ./wallet-service
    container_name: cropdeal-wallet-service
    restart: on-failure
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_wallet_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  order-service:
    build: ./order-service
    container_name: cropdeal-order-service
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  payment-service:
    build: ./payment-service
    container_name: cropdeal-payment-service
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  invoice-service:
    build: ./invoice-service
    container_name: cropdeal-invoice-service
    restart: on-failure
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_invoice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  delivery-service:
    build: ./deliveryservice
    container_name: cropdeal-delivery-service
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_delivery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  notification-service:
    build: ./notification-service
    container_name: cropdeal-notification-service
    restart: on-failure
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  chatbot-service:
    build: ./chatbot-service
    container_name: cropdeal-chatbot-service
    restart: on-failure
    ports:
      - "8093:8093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      - eureka-server
    networks:
      - cropdeal-net

  price-alert-service:
    build: ./price-alert-service
    container_name: cropdeal-price-alert-service
    restart: on-failure
    ports:
      - "8094:8094"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cropdeal_price_alert_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=naresh
      - SPRING_DATASOURCE_PASSWORD=vnaresh2004
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  report-service:
    build: ./report-service
    container_name: cropdeal-report-service
    restart: on-failure
    ports:
      - "8095:8095"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx140m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - cropdeal-net

  cropdeal-ui:
    build: ./cropdeal-ui
    container_name: cropdeal-ui
    restart: on-failure
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - cropdeal-net