<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.4</version>
        <relativePath/>
    </parent>

    <groupId>com.cropdeal</groupId>
    <artifactId>CropDeal</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>CropDeal</name>
    <description>CropDeal Microservices Ecosystem Parent Project</description>

    <properties>
        <java.version>21</java.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <springdoc.version>2.8.5</springdoc.version>
        <jjwt.version>0.12.6</jjwt.version>
    </properties>

    <modules>
        <module>config-server</module>
        <module>eureka-server</module>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>user-service</module>
        <module>price-service</module>
        <module>crop-service</module>
        <module>order-service</module>
        <module>payment-service</module>
        <module>delivery-service</module>
        <module>negotiation-service</module>
        <module>notification-service</module>
        <module>invoice-service</module>
        <module>chatbot-service</module>
        <module>admin-dashboard-report-service</module>
        <module>review-service</module>
        <module>bidding-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>