export interface Invoice {
  id: string;
  invoiceNumber: string;
  orderId: string;
  dealerId?: string | null;
  dealerName?: string | null;
  dealerPhone?: string | null;
  dealerAddress?: string | null;
  dealerGstin?: string | null;
  farmerId?: string | null;
  farmerName?: string | null;
  farmerPhone?: string | null;
  farmerAddress?: string | null;
  farmerPan?: string | null;
  cropName: string;
  cropVariety?: string;
  hsnCode?: string;
  quantity: number;
  unit?: string;
  pricePerUnit: number;
  govMspPrice?: number;
  totalAmount: number;
  taxAmount?: number;
  cgstAmount?: number;
  sgstAmount?: number;
  igstAmount?: number;
  fulfillmentType?: 'DELIVERY_AGENT' | 'SELF_PICKUP';
  deliveryFee?: number;
  deliveryDistanceKm?: number;
  deliveryAddress?: string;
  finalAmount: number;
  amountInWords?: string;
  paymentMethod?: string;
  transactionId?: string;
  status: 'PAID' | 'PENDING' | 'GENERATED';
  issuedAt: string;
  pdfUrl?: string;
}
