spring.application.name=user-service
server.port=8082

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/cropdeal_user_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=naresh
spring.datasource.password=vnaresh2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================================================
# EUREKA
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================================================
# AUTH SERVICE
# =========================================================

auth-service.url=http://localhost:8081

# Same secret used by Auth Service
jwt.secret=CropDealAuthServiceSecretKeyForJwtTokenGeneration2026Secure

# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================================================
# SWAGGER
# =========================================================

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html