server.port=8083
spring.datasource.url=${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/market_price?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
government.api.base-url=${GOVT_API_BASE_URL:https://api.data.gov.in}
government.api.resource-id=9ef84268-d588-465a-a308-a864a43d0070
government.api.key=${EXTERNAL_API_KEY:579b464db66ec23bdd0000019ccb1d11bdd742ad53d0ec97112d5fe4}
government.api.format=json
government.api.page-size=1000
government.api.sync-cron=0 0 2 * * *
government.api.sync-on-startup=false